name: Debug
on: [push]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(secrets) }}' > secrets.json
      - run: echo "$SECRETS"
        env:
          SECRETS: ${{ toJson(secrets) }}
